# Fonts
#
font_family Hack Nerd Font Mono
font_size 12

modify_font cell_height 115%
modify_font cell_width 100%

# Window
#
window_padding_width 0 15 15 15
tab_bar_margin_width 10
tab_bar_style powerline
enable_audio_bell no
placement_strategy center

# Ctrl and click to open a link
mouse_map ctrl+left press ungrabbed,grabbed mouse_click_url

# Mouse
mouse_hide_wait -1

# OS-specific overrides (loads kitty/linux.conf or kitty/macos.conf)
include ${KITTY_OS}.conf

# Theme
#
include ./themes/nord.conf