# Evergreen colors for Kitty

background #314a51
foreground #dbe1d5
selection_background #46394e
selection_foreground #dbe1d5
url_color #a8b88a
cursor #f09f0d

# Title bar
macos_titlebar_color #314a51

# Tabs
active_tab_background #f09f0d
active_tab_foreground #314a51
inactive_tab_background #3a5459
inactive_tab_foreground #80918f

# normal
color0 #314a51
color1 #bf616a
color2 #a8b88a
color3 #e08402
color4 #8fbcbb
color5 #bcc9a0
color6 #80918f
color7 #d8e0d5

# bright
color8 #566b6e
color9 #bf616a
color10 #95a876
color11 #f09f0d
color12 #8fbcbb
color13 #bcc9a0
color14 #b7c3b7
color15 #dbe1d5

# extended colors
color16 #c76b06
color17 #f8cf6e
